# serverless.yml
service: lambda
provider:
  name: aws
  region: us-east-2
  runtime: nodejs14.x
functions:
  copy-csv-to-postgres:
    # this is formatted as <FILENAME>.<HANDLER>
    # handler: index.handler
    handler: dist/index.handler
    events:
      - test: '{"bucket": "zip-unzip-bucket", "fileKey": "property_100.csv", "resetDb": false}'
      # - http:
      #     path: /
      #     method: post
      #     cors: true
      # - http:
      #     path: /
      #     method: get
      #     cors: true